# Generated by Django 5.0.4 on 2024-04-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='region',
            field=models.CharField(choices=[('uk', 'UK'), ('eu', 'Europe News'), ('w', 'World News')], max_length=10),
        ),
    ]
