# Generated by Django 5.0.4 on 2024-04-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_story_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('agency_code', models.CharField(max_length=5)),
            ],
        ),
    ]
